### ISSUE TITLE
The script should just automatically scrape the next server without prompting the user

### ISSUE THREAD

**Issue by ttx99** [Ciarands/vidsrc-to-resolver#11]
The script should just notify user if no content is found. More often than not user would wanna scrape the next server anyway.

**Comment by Ciarands** [comment]
It was a purposeful decision not to, keeping the fact that keys can be invalid in mind, I wanted to allow the user to wait a few minutes before retrying vidplay as a source so that the keys could have chance to update. 
This is why it prompts you to try the initial source again after trying the secondary source, I'll revisit this behavior in future after I finish my runtime key extractor.
