### ISSUE TITLE
Search Result found but wont play

### ISSUE THREAD

**Issue by ttx99** [Ciarands/vidsrc-to-resolver#4]
![Screenshot_2024-01-03_18-18-40](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/0ba91e04-3190-4584-b833-c5508f28bf82)
![Screenshot_2024-01-03_18-18-59](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/9efb43e7-82ac-4abd-9ad5-dfb74d2cfa0d)
![Screenshot_2024-01-03_18-18-18](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/1e2823b2-785d-494c-ae0e-f8e695daf5e0)
![Screenshot_2024-01-03_18-25-57](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/22892a10-ccbd-4c48-8828-41bbea31e049)

**Comment by Ciarands** [comment]
This is expected behavior, the search functionality is querying tmdb not vidsrc.to, only after the tmdb id is retrieved will it attempt to fetch from vidsrc.to, however it looks like I made an oversight in my "query_tmdb" function leading to an edge case which is returning the incorrect media-id in your case. For now,  please just manually pass the media-id, ill patch asap.
e.g
`python3 vidsrc.py -src "Vidplay" --media-id 840326 --media-type movie`

**Comment by ttx99** [comment]
thx for clarifying

**Comment by Ciarands** [comment]
Should be resolved now, basically just forgot to account for the fact that there can be multiple forms of media that share the same name, i'll probably end up making a cleaner sln though since its fairly difficult to differentiate.
